index:
    path: /
    defaults: { _controller: 'App\Controller\MainController::indexAction' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
